version: '3.7'

services:
  app:
    image: hub.tich.us/tawazz/crater
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./.env:/app/.env
      - ./storage/app/public:/app/public/storage
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    ports:
      - 8003:80
    networks:
      - crater

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      #- ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      - crater

  # nginx:
  #   image: nginx:1.17-alpine
  #   restart: unless-stopped
  #   ports:
  #     - 8001:80
  #   volumes:
  #     - ./:/var/www
  #     - ./storage/app/public:/var/www/public/storage
  #     - ./docker-compose/nginx:/etc/nginx/conf.d/
  #   networks:
  #     - crater

volumes:
  db:

networks:
  crater:
    driver: bridge
