version: '3.7'

services:
  app:
    build: .
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - ./storage/app/public:/app/public/storage
      - ./storage/app/public:/app/storage/app/public
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    ports:
      - 8001:80
    networks:
      - crater

  db:
    image: mariadb
    restart: always
    volumes:
      - ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      - crater

networks:
  crater:
    driver: bridge
